name: pots_trackr
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  # Architecture
  get: ^2.5.0
  get_it: ^4.0.2
  auto_route: ^0.5.0
  stacked: ^1.2.4
  stacked_services: ^0.2.4
  injectable: ^0.3.0

  # Logging
  catcher: ^0.3.6
  sentry: '>=3.0.0 <4.0.0'
  device_info: ^0.4.1+4

  # Firebase
  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.3
  cloud_firestore: ^0.13.5
  firebase_analytics: ^5.0.11

  # UI
  rflutter_alert: ^1.0.3
  flutter_form_builder: ^3.8.3
  flutter_signin_button: ^1.0.0
  font_awesome_flutter: ^8.8.1
  modal_progress_hud: ^0.1.3
#getflutter:

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  build_runner: ^1.10.0
  auto_route_generator: ^0.5.0
  injectable_generator: ^0.3.5
  firebase_core: ^0.4.4+3

flutter:
  uses-material-design: true
  assets:
    - assets/images/mountains.jpg
    - assets/images/full-bloom.png
